package qa;

import org.firstinspires.ftc.teamcode.lib.geometry.*;
import org.firstinspires.ftc.teamcode.pathing.*;

/**
 * Compiles a verbatim Path Planner output block against the real API, exercising
 * every heading mode the generator can emit. If the generator and the Java API
 * ever drift apart, this stops compiling.
 */
public class CodegenCompileTest {
    // A stand-in for the OpMode's `localization` so the pasted block type-checks.
    static class FakeLoc implements Localizer {
        Pose2d p = new Pose2d();
        public void update() {}
        public Pose2d getPose() { return p; }
        public void setStartingPose(Pose2d pose) { p = pose; }
    }
    static class NullDrive implements Drivetrain {
        public void driveFieldCentric(double a, double b, double c, Rotation2d h) {}
        public void stop() {}
    }

    public static void main(String[] args) {
        FakeLoc localization = new FakeLoc();
        Follower follower = new Follower(localization, new NullDrive());

        // ===== verbatim Path Planner output shape =====
        // Auto-generated by Path Planner. Field inches, heading degrees CCW.
        localization.setStartingPose(new Pose2d(-58.2, -35.7, Rotation2d.fromDegrees(90.0)));

        Path path0 = new Path(new BezierCurve(
                new Translation2d(-58.2, -35.7),
                new Translation2d(-20.5, -10.1),
                new Translation2d(12.3, 24.8)))
                .setTangentHeading();

        Path path1 = new Path(new BezierCurve(
                new Translation2d(12.3, 24.8),
                new Translation2d(40.0, 40.0)))
                .setLinearHeading(Math.toRadians(45.0), Math.toRadians(-90.0));

        Path path2 = new Path(new BezierCurve(
                new Translation2d(40.0, 40.0),
                new Translation2d(60.0, 10.0)))
                .setConstantHeading(Math.toRadians(0.0));

        Path path3 = new Path(new BezierCurve(
                new Translation2d(60.0, 10.0),
                new Translation2d(20.0, -20.0)))
                .setReverseTangentHeading();

        PathChain chain = new PathChain(path0, path1, path2, path3);
        follower.followPath(chain);
        // ===== end generated block =====

        System.out.println("Path Planner output compiles against the live API.");
        System.out.printf("   chain size = %d, follower busy = %s%n",
                chain.size(), follower.isBusy());
        for (int i = 0; i < chain.size(); i++) {
            Path p = chain.get(i);
            System.out.printf("   path%d: mode=%-8s len=%6.2f in  h(0)=%7.1f  h(1)=%7.1f deg%n",
                    i, p.getHeadingMode(), p.getTotalLength(),
                    Math.toDegrees(p.getHeading(0)), Math.toDegrees(p.getHeading(1)));
        }
        // Chain endpoints must be continuous, or the follower jumps between segments.
        boolean continuous = true;
        for (int i = 0; i + 1 < chain.size(); i++) {
            double gap = chain.get(i).getEndPoint().getDistance(chain.get(i + 1).getPoint(0));
            if (gap > 1e-6) { continuous = false; System.out.printf("   gap after path%d: %.3f in%n", i, gap); }
        }
        System.out.println(continuous ? "   segment endpoints are continuous."
                : "   **segments are discontinuous**");
    }
}
